#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart