#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World inside

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart