#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
sudo echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee file /var/www/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo echo "$server_config" | sudo tee file /etc/nginx/sites-enabled/default
sudo service nginx restart