#!/usr/bin/env bash
# This script installs and configures HAproxy

sudo apt update
sudo apt install haproxy -y
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 935-web-01 52.3.241.121:80 check\n\tserver 935-web-02 100.26.228.191:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
