#!/usr/bin/env bash
# This script enables nginx through port 80

sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo pkill -9 nginx
sudo service nginx start
