#!/usr/bin/env bash                                                            
# set up Nginx to run as nginx user                                                          
sudo pkill apache2
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart