#!/usr/bin/env bash
# Run nginx as nginx
sudo pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start